In [111]:
import pandas as pd
import numpy as np

In [112]:
import matplotlib.pyplot as plt
from sklearn import linear_model as lm
from sklearn.model_selection import train_test_split as tts
from sklearn.metrics import mean_squared_error as MSE

In [113]:
from sklearn.datasets import load_boston

In [114]:
boston = load_boston()

In [115]:
df_x = pd.DataFrame(boston.data, columns = boston.feature_names)
df_y = pd.DataFrame(boston.target)

In [116]:
df_x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
dtypes: float64(13)
memory usage: 51.5 KB

In [117]:
df_x.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000

In [118]:
LinReg = lm.LinearRegression()

In [119]:
x_train, x_test, y_train, y_test = tts(df_x, df_y, test_size = 0.31, random_state = 69)

In [120]:
LinReg.fit(x_train, y_train)

LinearRegression()

In [121]:
print(LinReg.coef_)

[[-1.45300555e-01  5.65074499e-02  3.60041879e-02  3.20926757e+00
  -1.80271759e+01  3.82817385e+00 -4.95640551e-04 -1.59091082e+00
   3.49382004e-01 -1.24928562e-02 -8.71581414e-01  1.19815082e-02
  -5.53608487e-01]]

In [122]:
predict_y = LinReg.predict(x_test)
print(predict_y)

[[28.40730735]
 [33.4251208 ]
 [19.26444716]
 [29.38819867]
 [29.74737281]
 [14.88407026]
 [18.8037628 ]
 [20.94843343]
 [12.09034491]
 [24.55953486]
 [20.41179291]
 [23.88240305]
 [19.40217362]
 [21.53093644]
 [16.76897502]
 [22.58104138]
 [20.24257742]
 [35.90972197]
 [28.96402786]
 [21.88477188]
 [17.90513181]
 [23.5783201 ]
 [21.93165717]
 [28.40461315]
 [20.61863896]
 [35.30601516]
 [16.10115886]
 [15.23297358]
 [15.99989969]
 [29.82630235]
 [-6.43132373]
 [27.68228629]
 [12.17950574]
 [28.19801784]
 [24.85490031]
 [28.41730765]
 [13.08172162]
 [13.65721142]
 [24.30018414]
 [27.07707475]
 [15.95688136]
 [16.12461757]
 [25.67515544]
 [18.34197833]
 [ 2.82779287]
 [30.0886339 ]
 [26.19576577]
 [20.23773278]
 [23.37377365]
 [23.69706188]
 [18.1844372 ]
 [30.73807028]
 [26.88782994]
 [22.04870187]
 [13.97686245]
 [30.40648315]
 [26.41093889]
 [ 3.25515432]
 [24.97407546]
 [29.51003931]
 [32.79220183]
 [21.96850935]
 [12.94251198]
 [32.95027074]
 [24.23259433]
 [25.9249452 ]
 [24.35964049]
 [22.62927782]
 [20.3110494 ]
 [35.68757847]
 [ 6.42947781]
 [28.60017783]
 [20.78378148]
 [19.08998929]
 [25.43326725]
 [40.87907202]
 [20.37861817]
 [37.8053064 ]
 [19.5993869 ]
 [20.53793109]
 [ 8.03222103]
 [27.49352233]
 [ 8.02027475]
 [17.79085615]
 [22.69273676]
 [28.81125254]
 [21.80819214]
 [28.76461845]
 [18.36460215]
 [ 7.8881692 ]
 [26.98199842]
 [30.84378726]
 [26.45917675]
 [22.17551693]
 [19.65138884]
 [16.70106258]
 [19.36277098]
 [21.10445329]
 [25.79233656]
 [15.89189559]
 [27.67627735]
 [22.93038041]
 [18.43567447]
 [33.90390319]
 [35.71079351]
 [14.23983763]
 [15.79042276]
 [13.95529262]
 [18.17526823]
 [19.98973816]
 [15.95066065]
 [11.47466117]
 [21.00605598]
 [32.16180842]
 [35.68161118]
 [17.50388258]
 [18.65131924]
 [39.13183702]
 [19.43395161]
 [31.16867781]
 [12.70059095]
 [19.75104338]
 [25.79997511]
 [32.18726194]
 [ 7.79125383]
 [24.00625712]
 [13.53280323]
 [23.2385746 ]
 [20.02289121]
 [19.82571129]
 [36.07185894]
 [20.97530599]
 [21.84646816]
 [12.93199939]
 [40.7303669 ]
 [27.05243763]
 [17.19715407]
 [22.19712618]
 [27.13520214]
 [16.93874244]
 [30.53242013]
 [24.94142928]
 [32.33228973]
 [24.44300983]
 [ 0.52843113]
 [19.86509628]
 [27.03673828]
 [20.72883116]
 [18.78333946]
 [42.47893339]
 [31.03563696]
 [41.21945308]
 [22.53917928]
 [13.52052022]
 [33.64083321]
 [38.22377877]
 [17.11985843]]

In [123]:
print(y_test)

        0
95   28.4
57   31.6
452  16.1
201  24.1
0    24.0
..    ...
6    22.9
23   14.5
187  32.0
232  41.7
211  19.3

[157 rows x 1 columns]

In [124]:
print(MSE(y_test, predict_y))

23.664279458878784